// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Pl5hc6xTIE6hSZs5a5Og7RJ9zba-FgA',
    appId: '1:683048404022:web:87f0994aa7030343f18497',
    messagingSenderId: '683048404022',
    projectId: 'full-app-project',
    authDomain: 'full-app-project.firebaseapp.com',
    storageBucket: 'full-app-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRFfKWf_2vrFhTLelpdL_qmYW3FTFv-Ss',
    appId: '1:683048404022:android:ccba5a08e7595050f18497',
    messagingSenderId: '683048404022',
    projectId: 'full-app-project',
    storageBucket: 'full-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Zspn2KovKYpIdPgeiByBKRr25CIzLTo',
    appId: '1:683048404022:ios:8494efacf08013aef18497',
    messagingSenderId: '683048404022',
    projectId: 'full-app-project',
    storageBucket: 'full-app-project.appspot.com',
    iosBundleId: 'com.livegate.app',
  );
}
